import type {
  DashboardStats,
  Publication,
  Reviewer,
  ScheduleIssue,
  Submission,
} from "./types";

export const publicStats: DashboardStats = {
  totalSubmissions: 1247,
  underReview: 86,
  publishedPapers: 892,
  activeReviewers: 48,
};

export const adminStats: DashboardStats = {
  totalSubmissions: 1247,
  underReview: 86,
  publishedPapers: 892,
  activeReviewers: 48,
};

export const submissions: Submission[] = [
  {
    id: "1",
    trackingCode: "PAOM-2026-A3F9K2",
    title: "Digital Transformation in Philippine SMEs: A Longitudinal Study",
    authors: ["Maria Santos", "Juan Dela Cruz"],
    affiliation: "University of the Philippines Diliman",
    abstract:
      "This study examines the adoption patterns of digital technologies among small and medium enterprises in the Philippines over a five-year period.",
    keywords: ["digital transformation", "SMEs", "Philippines"],
    status: "under_review",
    submittedAt: "2026-01-15",
    reviewerId: "r1",
    email: "maria.santos@up.edu.ph",
  },
  {
    id: "2",
    trackingCode: "PAOM-2026-B7X2M1",
    title: "Leadership Styles and Organizational Resilience Post-Pandemic",
    authors: ["Ana Reyes"],
    affiliation: "Ateneo de Manila University",
    abstract:
      "An empirical analysis of how transformational and servant leadership styles influenced organizational resilience during and after the COVID-19 pandemic.",
    keywords: ["leadership", "resilience", "pandemic"],
    status: "submitted",
    submittedAt: "2026-02-28",
    email: "ana.reyes@ateneo.edu",
  },
  {
    id: "3",
    trackingCode: "PAOM-2026-C1P8N4",
    title: "Sustainable Supply Chain Practices in ASEAN Manufacturing",
    authors: ["Carlos Mendoza", "Lisa Tan"],
    affiliation: "De La Salle University",
    abstract:
      "This paper investigates sustainable supply chain management practices adopted by manufacturing firms across ASEAN member states.",
    keywords: ["supply chain", "sustainability", "ASEAN"],
    status: "revision",
    submittedAt: "2025-11-20",
    reviewerId: "r2",
    email: "carlos.m@dlsu.edu.ph",
  },
  {
    id: "4",
    trackingCode: "PAOM-2025-D4Q6R9",
    title: "Corporate Governance and Firm Performance in Listed Philippine Companies",
    authors: ["Roberto Garcia"],
    affiliation: "University of Santo Tomas",
    abstract:
      "A quantitative study examining the relationship between corporate governance indices and financial performance metrics.",
    keywords: ["corporate governance", "firm performance"],
    status: "accepted",
    submittedAt: "2025-09-10",
    reviewerId: "r3",
    email: "r.garcia@ust.edu.ph",
  },
  {
    id: "5",
    trackingCode: "PAOM-2025-E2S5T7",
    title: "Entrepreneurial Ecosystem Development in Metro Manila",
    authors: ["Patricia Lim", "Mark Villanueva"],
    affiliation: "Asian Institute of Management",
    abstract:
      "This research maps the entrepreneurial ecosystem in Metro Manila and identifies key enablers and barriers to startup growth.",
    keywords: ["entrepreneurship", "ecosystem", "startups"],
    status: "published",
    submittedAt: "2025-06-01",
    reviewerId: "r1",
    email: "p.lim@aim.edu",
  },
  {
    id: "6",
    trackingCode: "PAOM-2026-F8U3V2",
    title: "Work-Life Balance Policies in Hybrid Work Environments",
    authors: ["Grace Fernandez"],
    affiliation: "University of San Carlos",
    abstract:
      "An exploratory study on the effectiveness of work-life balance policies in organizations adopting hybrid work models.",
    keywords: ["work-life balance", "hybrid work", "HR policies"],
    status: "under_review",
    submittedAt: "2026-03-01",
    reviewerId: "r4",
    email: "g.fernandez@usc.edu.ph",
  },
];

export const reviewers: Reviewer[] = [
  {
    id: "r1",
    name: "Dr. Elena Villanueva",
    affiliation: "University of the Philippines",
    expertise: ["Strategic Management", "Digital Transformation", "SMEs"],
    availability: "available",
    activeReviews: 3,
    email: "e.villanueva@up.edu.ph",
    deadline: "2026-04-15",
  },
  {
    id: "r2",
    name: "Prof. Michael Ong",
    affiliation: "Ateneo de Manila University",
    expertise: ["Supply Chain", "Operations Management", "Sustainability"],
    availability: "limited",
    activeReviews: 5,
    email: "m.ong@ateneo.edu",
    deadline: "2026-03-30",
  },
  {
    id: "r3",
    name: "Dr. Sofia Ramirez",
    affiliation: "De La Salle University",
    expertise: ["Corporate Governance", "Finance", "Ethics"],
    availability: "available",
    activeReviews: 2,
    email: "s.ramirez@dlsu.edu.ph",
    deadline: "2026-05-01",
  },
  {
    id: "r4",
    name: "Prof. James Tan",
    affiliation: "Asian Institute of Management",
    expertise: ["Human Resources", "Organizational Behavior", "Leadership"],
    availability: "available",
    activeReviews: 4,
    email: "j.tan@aim.edu",
    deadline: "2026-04-01",
  },
  {
    id: "r5",
    name: "Dr. Patricia Cruz",
    affiliation: "University of Santo Tomas",
    expertise: ["Entrepreneurship", "Innovation", "Marketing"],
    availability: "unavailable",
    activeReviews: 0,
    email: "p.cruz@ust.edu.ph",
  },
  {
    id: "r6",
    name: "Prof. Daniel Reyes",
    affiliation: "University of San Carlos",
    expertise: ["International Business", "ASEAN Studies", "Trade"],
    availability: "limited",
    activeReviews: 3,
    email: "d.reyes@usc.edu.ph",
    deadline: "2026-04-20",
  },
];

export const publications: Publication[] = [
  {
    id: "p1",
    title: "Entrepreneurial Ecosystem Development in Metro Manila",
    authors: ["Patricia Lim", "Mark Villanueva"],
    year: 2025,
    category: "Entrepreneurship",
    status: "published",
    doi: "10.1234/paom.2025.001",
    keywords: ["entrepreneurship", "ecosystem"],
  },
  {
    id: "p2",
    title: "Corporate Social Responsibility and Brand Equity in Filipino Firms",
    authors: ["Angela Morales"],
    year: 2025,
    category: "Marketing",
    status: "published",
    doi: "10.1234/paom.2025.002",
    keywords: ["CSR", "brand equity"],
  },
  {
    id: "p3",
    title: "Agile Project Management in Government IT Initiatives",
    authors: ["Ricardo Santos", "Liza Gomez"],
    year: 2024,
    category: "Project Management",
    status: "published",
    doi: "10.1234/paom.2024.015",
    keywords: ["agile", "government", "IT"],
  },
  {
    id: "p4",
    title: "Financial Inclusion Through Fintech in Rural Philippines",
    authors: ["Henry Bautista"],
    year: 2024,
    category: "Finance",
    status: "published",
    doi: "10.1234/paom.2024.022",
    keywords: ["fintech", "financial inclusion"],
  },
  {
    id: "p5",
    title: "Women in Leadership: Barriers and Enablers in Southeast Asia",
    authors: ["Carmen Flores", "Nina Aquino"],
    year: 2024,
    category: "Leadership",
    status: "published",
    doi: "10.1234/paom.2024.031",
    keywords: ["women", "leadership", "Southeast Asia"],
  },
  {
    id: "p6",
    title: "Corporate Governance and Firm Performance in Listed Philippine Companies",
    authors: ["Roberto Garcia"],
    year: 2026,
    category: "Corporate Governance",
    status: "in_press",
    keywords: ["corporate governance", "performance"],
  },
];

export const scheduleIssues: ScheduleIssue[] = [
  {
    id: "s1",
    volume: "12",
    issue: "1",
    releaseDate: "2026-06-30",
    submissionDeadline: "2026-03-31",
    progress: 60,
    status: "open",
    isPublic: true,
  },
  {
    id: "s2",
    volume: "11",
    issue: "4",
    releaseDate: "2026-03-15",
    submissionDeadline: "2025-12-15",
    progress: 90,
    status: "production",
    isPublic: true,
  },
  {
    id: "s3",
    volume: "11",
    issue: "3",
    releaseDate: "2025-12-01",
    submissionDeadline: "2025-09-01",
    progress: 100,
    status: "published",
    isPublic: true,
  },
  {
    id: "s4",
    volume: "12",
    issue: "2",
    releaseDate: "2026-12-15",
    submissionDeadline: "2026-09-30",
    progress: 15,
    status: "planning",
    isPublic: false,
  },
];

export const monthlySubmissions = [
  { month: "Oct", count: 42 },
  { month: "Nov", count: 58 },
  { month: "Dec", count: 35 },
  { month: "Jan", count: 67 },
  { month: "Feb", count: 81 },
  { month: "Mar", count: 74 },
];

export const statusDistribution = [
  { name: "Submitted", value: 24, color: "#1E22AA" },
  { name: "Under Review", value: 86, color: "#F4D400" },
  { name: "Revision", value: 18, color: "#FF8C00" },
  { name: "Accepted", value: 32, color: "#22C55E" },
  { name: "Published", value: 892, color: "#FF0000" },
];
